inherit_from: .rubocop_todo.yml

inherit_gem:
  main_branch_shared_rubocop_config: config/rubocop.yml

# Don't care about CyclomaticComplexity or AbcSize in TestUnit tests This should go
# away when we switch to RSpec.
Metrics/CyclomaticComplexity:
  Exclude:
    - "tests/test_helper.rb"
    - "tests/units/**/*"

Metrics/AbcSize:
  Exclude:
    - "tests/test_helper.rb"
    - "tests/units/**/*"

# Don't care so much about length of methods in tests
Metrics/MethodLength:
  Exclude:
    - "tests/test_helper.rb"
    - "tests/units/**/*"

# Allow test data to have long lines
Layout/LineLength:
  Exclude:
    - "tests/test_helper.rb"
    - "tests/units/**/*"
    - "*.gemspec"

# Testing and gemspec DSL results in large blocks
Metrics/BlockLength:
  Exclude:
    - "tests/test_helper.rb"
    - "tests/units/**/*"
    - "*.gemspec"

# Don't force every test class to be described
Style/Documentation:
  Exclude:
    - "tests/units/**/*"

AllCops:
  # Pin this project to Ruby 3.1 in case the shared config above is upgraded to 3.2
  # or later.
  TargetRubyVersion: 3.2
