# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "git"
  s.version = "1.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Chacon"]
  s.date = "2012-12-03"
  s.email = "schacon@gmail.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/git.rb",
    "lib/git/author.rb",
    "lib/git/base.rb",
    "lib/git/branch.rb",
    "lib/git/branches.rb",
    "lib/git/diff.rb",
    "lib/git/index.rb",
    "lib/git/lib.rb",
    "lib/git/log.rb",
    "lib/git/object.rb",
    "lib/git/path.rb",
    "lib/git/remote.rb",
    "lib/git/repository.rb",
    "lib/git/stash.rb",
    "lib/git/stashes.rb",
    "lib/git/status.rb",
    "lib/git/working_directory.rb"
  ]
  s.homepage = "http://github.com/schacon/ruby-git"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.requirements = ["git 1.6.0.0, or greater"]
  s.rubyforge_project = "git"
  s.rubygems_version = "1.8.23"
  s.summary = "Ruby/Git is a Ruby library that can be used to create, read and manipulate Git repositories by wrapping system calls to the git binary"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

